name: foodking_admin
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+9

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  image_picker: ^1.1.2
  get_storage: ^2.1.1
  flutter_svg: ^2.0.5
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.2
  bottom_bar: ^2.0.3
  flutter_staggered_grid_view: ^0.7.0
  percent_indicator: ^4.2.3
  google_maps_flutter: ^2.5.0
  webview_flutter: ^4.2.4
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  dio: ^5.3.2
  intl: ^0.20.1
  firebase_messaging: ^15.1.6
  firebase_core: ^3.9.0
  flutter_local_notifications: ^18.0.1
  lottie: ^3.2.0
  path_provider:
  permission_handler:
  printing: ^5.12.0
  # create pdf document
  pdf: ^3.1.0
  # open pdf document
  open_file: ^3.1.0
  win32: ^5.5.3
  archive: ^3.6.1
  url_launcher: ^6.1.10
  flutter_html:

  fl_chart:
    git:
      url: https://github.com/mdkhaledhassan/fl_chart_0.40.6.git




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animation/
